# Generated by Django 4.2.8 on 2025-04-06 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HangHoa',
            fields=[
                ('ma_hang', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã hàng')),
                ('ten_hang', models.CharField(max_length=255, verbose_name='Tên hàng')),
                ('nhom_hang', models.CharField(max_length=100, verbose_name='Nhóm hàng')),
                ('url_image', models.ImageField(blank=True, null=True, upload_to='images/hanghoa/', verbose_name='Ảnh sản phẩm')),
                ('don_vi_tinh', models.CharField(max_length=50, verbose_name='Đơn vị tính')),
                ('han_su_dung', models.DateField(blank=True, null=True, verbose_name='Hạn sử dụng')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Hàng Hóa',
                'verbose_name_plural': 'Hàng Hóa',
                'ordering': ['ten_hang'],
            },
        ),
        migrations.CreateModel(
            name='TonKho',
            fields=[
                ('hang_hoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ton_kho', serialize=False, to='cuoiky.hanghoa', verbose_name='Hàng hóa')),
                ('so_luong_he_thong', models.PositiveIntegerField(default=0, verbose_name='Số lượng hệ thống')),
                ('tinh_trang', models.CharField(choices=[('CON_HANG', 'Còn hàng'), ('GAN_HET_HANG', 'Gần hết hàng'), ('HET_HANG', 'Hết hàng')], default='CON_HANG', max_length=50, verbose_name='Tình trạng tồn cuoiky')),
            ],
            options={
                'verbose_name': 'Tồn Kho',
                'verbose_name_plural': 'Tồn Kho',
            },
        ),
        migrations.CreateModel(
            name='XuatKho',
            fields=[
                ('ma_xuat', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã phiếu xuất')),
                ('nguon_nhan', models.CharField(max_length=255, verbose_name='Nguồn nhận')),
                ('thoi_gian', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian xuất')),
                ('tinh_trang', models.CharField(choices=[('CHO_DUYET', 'Chờ duyệt'), ('DA_DUYET', 'Đã duyệt'), ('DA_XUAT', 'Đã xuất'), ('TU_CHOI', 'Từ chối'), ('HOAN_HANG', 'Hoàn hàng')], default='CHO_DUYET', max_length=50, verbose_name='Tình trạng phiếu')),
                ('tong', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Tổng tiền')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo phiếu')),
                ('sdt', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('diachi', models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ')),
                ('ly_do', models.TextField(blank=True, null=True, verbose_name='Lý do xuất')),
                ('url_hop_dong', models.FileField(blank=True, null=True, upload_to='files/xuatkho/hopdong/', verbose_name='File hợp đồng')),
                ('url_so_cu', models.FileField(blank=True, null=True, upload_to='files/xuatkho/socu/', verbose_name='File sổ cũ')),
                ('tao_boi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phieu_xuat_kho', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Phiếu Xuất Kho',
                'verbose_name_plural': 'Phiếu Xuất Kho',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='NhapKho',
            fields=[
                ('ma_nhap', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã phiếu nhập')),
                ('nguon_nhap', models.CharField(max_length=255, verbose_name='Nguồn nhập')),
                ('thoi_gian', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian nhập')),
                ('tinh_trang', models.CharField(choices=[('CHO_DUYET', 'Chờ duyệt'), ('DA_DUYET', 'Đã duyệt'), ('DA_NHAP', 'Đã nhập'), ('TU_CHOI', 'Từ chối')], default='CHO_DUYET', max_length=50, verbose_name='Tình trạng phiếu')),
                ('tong', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Tổng tiền')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo phiếu')),
                ('sdt', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('diachi', models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ')),
                ('ly_do', models.TextField(blank=True, null=True, verbose_name='Lý do nhập')),
                ('url_hop_dong', models.FileField(blank=True, null=True, upload_to='files/nhapkho/hopdong/', verbose_name='File hợp đồng')),
                ('url_so_cu', models.FileField(blank=True, null=True, upload_to='files/nhapkho/socu/', verbose_name='File sổ cũ')),
                ('tao_boi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phieu_nhap_kho', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Phiếu Nhập Kho',
                'verbose_name_plural': 'Phiếu Nhập Kho',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='KiemKe',
            fields=[
                ('ma_kiemke', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã kiểm kê')),
                ('muc_dich', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mục đích')),
                ('thoi_gian', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian kiểm kê')),
                ('tinh_trang', models.CharField(choices=[('CHO_DUYET', 'Chờ duyệt'), ('DA_DUYET', 'Đã duyệt'), ('TU_CHOI', 'Từ chối')], default='CHO_DUYET', max_length=50, verbose_name='Tình trạng phiếu')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo phiếu')),
                ('tao_boi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phieu_kiem_ke', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Phiếu Kiểm Kê',
                'verbose_name_plural': 'Phiếu Kiểm Kê',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietXuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('don_gia_xuat', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Đơn giá xuất')),
                ('so_luong_xuat', models.PositiveIntegerField(verbose_name='Số lượng xuất')),
                ('chiet_khau', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Chiết khấu')),
                ('thanh_tien', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Thành tiền')),
                ('ma_hang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_xuat', to='cuoiky.hanghoa', verbose_name='Mã hàng')),
                ('ma_xuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_xuat', to='cuoiky.xuatkho', verbose_name='Mã phiếu xuất')),
            ],
            options={
                'verbose_name': 'Chi Tiết Xuất Kho',
                'verbose_name_plural': 'Chi Tiết Xuất Kho',
                'ordering': ['ma_xuat', 'ma_hang'],
                'unique_together': {('ma_xuat', 'ma_hang')},
            },
        ),
        migrations.CreateModel(
            name='ChiTietNhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('don_gia_nhap', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Đơn giá nhập')),
                ('so_luong_nhap', models.PositiveIntegerField(verbose_name='Số lượng nhập')),
                ('chiet_khau', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Chiết khấu')),
                ('thanh_tien', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Thành tiền')),
                ('ma_hang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_nhap', to='cuoiky.hanghoa', verbose_name='Mã hàng')),
                ('ma_nhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_nhap', to='cuoiky.nhapkho', verbose_name='Mã phiếu nhập')),
            ],
            options={
                'verbose_name': 'Chi Tiết Nhập Kho',
                'verbose_name_plural': 'Chi Tiết Nhập Kho',
                'ordering': ['ma_nhap', 'ma_hang'],
                'unique_together': {('ma_nhap', 'ma_hang')},
            },
        ),
        migrations.CreateModel(
            name='ChiTietKiemKe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_he_thong', models.PositiveIntegerField(verbose_name='Số lượng hệ thống (lúc KK)')),
                ('so_luong_tai_kho', models.PositiveIntegerField(verbose_name='Số lượng thực tế')),
                ('chenh_lech', models.IntegerField(editable=False, verbose_name='Chênh lệch')),
                ('xu_ly', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hướng xử lý')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_kiem_ke', to='cuoiky.hanghoa', verbose_name='Hàng hóa')),
                ('phieu_kiem_ke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_kiem_ke', to='cuoiky.kiemke', verbose_name='Phiếu kiểm kê')),
            ],
            options={
                'verbose_name': 'Chi Tiết Kiểm Kê',
                'verbose_name_plural': 'Chi Tiết Kiểm Kê',
                'ordering': ['phieu_kiem_ke', 'hang_hoa'],
                'unique_together': {('phieu_kiem_ke', 'hang_hoa')},
            },
        ),
    ]
