# Generated by Django 4.2.8 on 2025-04-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuoiky', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hanghoa',
            name='so_luong_he_thong',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng hệ thống'),
        ),
        migrations.AddField(
            model_name='hanghoa',
            name='tinh_trang',
            field=models.CharField(choices=[('CON_HANG', 'Còn hàng'), ('GAN_HET_HANG', 'Gần hết hàng'), ('HET_HANG', 'Hết hàng')], default='CON_HANG', max_length=50, verbose_name='Tình trạng tồn cuoiky'),
        ),
        migrations.DeleteModel(
            name='TonKho',
        ),
    ]
