# Generated by Django 4.2.8 on 2025-04-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuoiky', '0002_hanghoa_so_luong_he_thong_hanghoa_tinh_trang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhapkho',
            name='ngay_tao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='nhapkho',
            name='thoi_gian',
            field=models.DateTimeField(),
        ),
    ]
