# Generated by Django 4.2.8 on 2025-04-07 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cuoiky', '0003_alter_nhapkho_ngay_tao_alter_nhapkho_thoi_gian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhapkho',
            name='ngay_tao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo phiếu'),
        ),
        migrations.AlterField(
            model_name='nhapkho',
            name='thoi_gian',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian nhập'),
        ),
    ]
