# Generated by Django 4.2.20 on 2025-05-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuoiky', '0005_customuser'),
    ]

    operations = [
    ]
